### ISSUE TITLE
Suit count incorrect

### ISSUE THREAD

**Issue by thorfour** [seiyria/OathParser#1]
For some seeds I've noticed that the reported suit count is incorrect.

ex: 
```
03020000071BThe Chrysanthemum Chronicle00000201234516FFFFE121FFFFFF06FFFFE92BFFFFFF22FFFFFF1AFFFFFF29FFFFFF05CD2FFF3A0BD5BF554761C4D32DBB22215A1DA1D663D406A350AE180D1232D246A833152328B4B6B2526C04251EA637119627105153B36A0A039EB5A45626241B1C17002C1424342A1A20354A090E132E1F54BD0CC508070F2BC39A021619052931300112E4E3E0E2DBEDEBECDFDAE7EADCDDE5DEE6E8
```
![suits](https://user-images.githubusercontent.com/8681572/105533439-c2acbf80-5cb1-11eb-87af-dceff3f7c23d.png)

but on TTS

![suits_tts](https://user-images.githubusercontent.com/8681572/105533516-dc4e0700-5cb1-11eb-8289-00c483d45a4e.png)

You can see there are 2 more discord cards in the deck then reported

**Comment by thorfour** [comment]
~Digging a little further I found the follow:~
<redacted>
 
 Edit: realized I ran the parse on the wrong string

**Comment by seiyria** [comment]
Hmm:

- Gossip: https://github.com/Vagabottos/OathParser/blob/master/src/interfaces/cards.ts#L101
- Silver Tongue: https://github.com/Vagabottos/OathParser/blob/master/src/interfaces/cards.ts#L94
- Assassin: https://github.com/Vagabottos/OathParser/blob/master/src/interfaces/cards.ts#L94

Looks like the parser is only missing sneak attack?

**Comment by thorfour** [comment]
and there's a slot for `Surprise Attack` in the index that I don't think exitsts as a card?

I'm assuming this is supposed to be sneak attack?

**Comment by seiyria** [comment]
Ah, yes, it was renamed. It's possible that some card names changed and I missed the update - I had to update them in 3 places when I got updates.

**Comment by thorfour** [comment]
Other suits are slightly incorrect as well
```
ex: Order

TTS: Peace Envoy
Parser: missing
```

**Comment by thorfour** [comment]
So running the parser on the correct one, I see all 15 discord in the parser.

**Comment by thorfour** [comment]
So this may actually be an Oath.Vision bug

**Comment by thorfour** [comment]
Well looking at Oath.Vision since you have Sneak Attack there and Surprise Attack in the parser, I assume that's at least 1 of missing counts.

**Comment by seiyria** [comment]
Thanks! Definitely was tough updating it in 3 places and keeping it
consistent, I'm glad you nailed down what it was so quickly.

**Comment by thorfour** [comment]
https://oath.vision/preview-chronicle?seed=03020000081BThe%20Chrysanthemum%20Chronicle0008010123450903CCDD0AFFDCFF01FFFFFF18FFFFFF29FFFFFF0CFFFFE720FFFFFF1AFFFFFF3926D6D46323B33A11B6066CA40447D51518A8533741D30BD27C2D27519646AE5A5BB2250A22A3A64FB49E6A1E32C42855BF62101261BB52B5332A1B1C17002C1424342A1A20354A090E132E1F54BD0CC508070F2BC39A02161905293130010D50A121561D11E2E4EDEAECDFE9E0DAEBE3E1DBE8E5DEE6

Looks like we're only missing one now

**Comment by seiyria** [comment]
I think oath.vision might need a quick update to use the new version of oathparser, and I need to quick publish one. give me a few minutes and check in after that!

**Comment by thorfour** [comment]
Looks fixed! Thanks!
